exclude = ["target/*"]
include = ["**/*.toml"]

[formatting]
column_width = 100

[[rule]]
include = ["**/Cargo.toml"]
keys = ["workspace.lints.*", "workspace.dependencies", "dependencies", "*-dependencies"]

[rule.formatting]
reorder_keys = true

[[rule]]
include = ["**/Cargo.toml"]
keys = [
  "workspace.*-dependencies",
  "workspace.*-dependencies.*",
  "dependencies.*",
  "*-dependencies.*",
]

[rule.formatting]
reorder_keys = false
