[package]
name = "protobug"
version = "0.1.0"
authors.workspace = true
edition.workspace = true
rust-version.workspace = true

[dependencies]
anyhow = "1"
base64 = { workspace = true }
camino = { workspace = true }
clap = { workspace = true, features = ["derive"] }
crossterm = { workspace = true }
derive_more = { version = "2", features = ["display", "error"] }
error-stack = { workspace = true, features = ["anyhow"] }
hex = { workspace = true }
protobuf = { workspace = true }
protobuf-json-mapping = "3"
protobuf-parse = "3"
ratatui = { workspace = true }
serde_json = "1"
tui-textarea = "0.7"

[dev-dependencies]
indoc = "2"
pretty_assertions = "1"

[lints]
workspace = true
