[package]
name = "protobug"
version = "0.1.0"
authors.workspace = true
edition.workspace = true
rust-version.workspace = true

[dependencies]
anyhow = "1"
base64 = "0.22"
camino = "1"
clap = { version = "4", features = ["derive"] }
crossterm = "0.27"
derive_more = "0.99.18"
error-stack = { version = "0.4", features = ["anyhow"] }
hex = "0.4"
protobuf = "3"
protobuf-json-mapping = "3"
protobuf-parse = "3"
ratatui = "0.26"
serde_json = "1"
tui-textarea = "0.4"

[dev-dependencies]
indoc = "2"
pretty_assertions = "1"

[lints]
workspace = true
