name: CD

on:
  release:
    types: [published]

permissions:
  contents: write

env:
  CARGO_INCREMENTAL: 0
  CARGO_NET_GIT_FETCH_WITH_CLI: true
  CARGO_NET_RETRY: 10
  CARGO_TERM_COLOR: always
  RUST_BACKTRACE: 1
  RUSTUP_MAX_RETRIES: 10

defaults:
  run:
    shell: bash

jobs:
  upload-assets:
    strategy:
      fail-fast: false
      matrix:
        include:
          - { os: macos-latest, target: aarch64-apple-darwin }
          - { os: macos-latest, target: universal-apple-darwin }
          - { os: macos-latest, target: x86_64-apple-darwin }
          - { os: ubuntu-latest, target: aarch64-unknown-linux-gnu }
          - { os: ubuntu-latest, target: aarch64-unknown-linux-musl }
          - { os: ubuntu-latest, target: x86_64-unknown-freebsd }
          - { os: ubuntu-latest, target: x86_64-unknown-linux-gnu }
          - { os: ubuntu-latest, target: x86_64-unknown-linux-musl }
          - { os: windows-latest, target: aarch64-pc-windows-msvc }
          - { os: windows-latest, target: x86_64-pc-windows-msvc }

    name: Deploy (${{ matrix.target }})
    runs-on: ${{ matrix.os }}
    if: github.repository_owner == 'robjtede' && startsWith(github.event.release.name, 'v')
    timeout-minutes: 60

    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - name: Install Rust
        uses: actions-rust-lang/setup-rust-toolchain@a0b538fa0b742a6aa35d6e2c169b4bd06d225a98 # v1.15.3
        with:
          cache: false

      # TODO: see if this is needed after next deploy
      # - if: startsWith(matrix.os, 'ubuntu') && !endsWith(matrix.target, '-musl')
      - uses: taiki-e/setup-cross-toolchain-action@b8d1a322a6009a2b7220f53996695778eef89b41 # v1.38.0
        with:
          target: ${{ matrix.target }}

      # TODO: see if this is needed after next deploy
      # - if: endsWith(matrix.target, '-musl')
      #   uses: taiki-e/install-action@v2.23.1
      #   with:
      #     tool: cross

      # TODO: see if this is needed after next deploy
      # - if: endsWith(matrix.target, 'windows-msvc')
      #   run: echo "RUSTFLAGS=${RUSTFLAGS} -C target-feature=+crt-static" >> "${GITHUB_ENV}"

      - name: Build and upload to release
        id: upload-release
        uses: taiki-e/upload-rust-binary-action@f391289bcff6a7f36b6301c0a74199657bbb4561 # v1.28.0
        with:
          bin: protobug
          target: ${{ matrix.target }}
          tar: all
          zip: all
          checksum: sha256,sha512
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Generate artifact attestation
        uses: actions/attest-build-provenance@a2bbfa25375fe432b6a289bc6b6cd05ecd0c4c32 # v4.1.0
        with:
          subject-path: ${{ steps.upload-release.outputs.zip }}
